name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        sudo npm install -g ionic
        sudo npm install -g cordova
        npm i
        ionic cordova platform add android
        ionic cordova build android
